### ISSUE TITLE
Add a date filter - Items between start date and end date

### ISSUE THREAD

**Issue by LeaBits** [TimGeyssens/UIOMatic#139]
Hello! I'm really loving this package so far! I'm using UIOMatic on multiple projects at the moment and in one of our projects there is a need for filtering between dates.

For more details, here is our use case:
I'm saving reservations in a Peta Poco model. In de UIOMatic section, in the list view, they would like to know what the next reservations are or maybe even what the reservations for next week or next month are. So I would like the possibility to filter one DateTime variable between two dates.

Is there anyone who has an idea on how to do this? I've tried to fiddle with custom filters, but since the UIOMatic api requires a key and value, I can't seem to make it work.

**Comment by Sibren** [comment]
Hi Leanne,

I guess for now this would require some custom coding, not out of the box.
Maybe check out the listview and override it with your own implementation, where you can pick dates too.

This shouldn't be too hard, I guess?
If you go to /App_Plugins/UIOMatic/backoffice/uiomatic/list.html and the corresponding list.controller.js, maybe you can start from there?
This would require the need to wire up some kind of custom API controller, though, because the fetchData-function in list.controller.js doesn't get this.
I don't have any code from myself at this moment, but you can check out the Exporter Tim built.
https://github.com/TimGeyssens/UIOMatic-Addons-Export/blob/master/src/UIOMaticAddons.Export/Controllers/ExportController.cs

**Comment by TimGeyssens** [comment]
Super late reply but this is possible by default, you can just add another ui o matic class and then use the event model to set a custom sql filter... check this example for event model uses to control the query http://www.nibble.be/?p=493
