### ISSUE TITLE
Field view controllers, check for duplicate init calls

### ISSUE THREAD

**Issue by TimGeyssens** [TimGeyssens/UIOMatic#62]
Now that the broadcast is working again it seems several controllers call the init method to quickly

**Comment by mattbrailsford** [comment]
Which ones are firing too quickly?

**Comment by TimGeyssens** [comment]
Need to check but I've seen that a couple have this code:

```
function init(){....//do stuff here };

    init();

    $scope.$on('valuesLoaded', function (event, data) {
        init();
    });
```
So I think the first init() call can be removed since it is best to wait until the values have loaded

**Comment by TimGeyssens** [comment]
But I can take a look at this one :) will test if they all work

**Comment by mattbrailsford** [comment]
Gotcha!

**Comment by mattbrailsford** [comment]
I think we may need to allow multiple calls because I have noticed some views not initializing on load. What I think is happening is that some of the views are loading in after valuesLoaded is fired so when they do finish loading in, nothing triggers the initialization. 

As scopes are inherited and editors should be children of the edit controller, maybe we should set a variable to say valuesLoaded as well and within editors, check that value, and if it's true, just fire the init method straight away, otherwise wait for valuesLoaded event to fire?

**Comment by TimGeyssens** [comment]
Yeah could be a good option, just in the progress of another test round, will check all of the editors and report back

**Comment by mattbrailsford** [comment]
Just to add to this, we should probably look at making sure we remove the event listeners on destruction, and probably after the first run too, so something like this

    var removeValuesLoadedListener = $scope.$on('valuesLoaded ', function()
    {
        init();
        removeValuesLoadedListener();
    });

    $scope.$on('$destroy ', function()
    {
        removeValuesLoadedListener();
    });
